// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDX9Wf7A69FCAeksL_ZnN1NPe_mQbaX1Y',
    appId: '1:883572288266:web:a2503699607717d0a468f3',
    messagingSenderId: '883572288266',
    projectId: 'bhr-quotes',
    authDomain: 'bhr-quotes.firebaseapp.com',
    databaseURL: 'https://bhr-quotes.firebaseio.com',
    storageBucket: 'bhr-quotes.appspot.com',
    measurementId: 'G-C8BFBKKG30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDngtspCMXh6-jk-8q_fSF1vkKFF9bKvgM',
    appId: '1:883572288266:android:58d5912e242e5bc5a468f3',
    messagingSenderId: '883572288266',
    projectId: 'bhr-quotes',
    databaseURL: 'https://bhr-quotes.firebaseio.com',
    storageBucket: 'bhr-quotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADd-DwAC2p03xVLGsk34MhNvSNWAYDONI',
    appId: '1:883572288266:ios:0229ae3c50fc8400a468f3',
    messagingSenderId: '883572288266',
    projectId: 'bhr-quotes',
    databaseURL: 'https://bhr-quotes.firebaseio.com',
    storageBucket: 'bhr-quotes.appspot.com',
    iosClientId: '883572288266-idmnj48l4ju16agejrsets7bjekfvj6b.apps.googleusercontent.com',
    iosBundleId: 'com.bhrs.quotes.bhrQuotes',
  );
}
